name: run-script
on: push

jobs:
  run_build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run build script file
      run: |
         chmod +x ./scripts/prebuild.sh
         chmod +x ./scripts/build.sh
         ./scripts/prebuild.sh
         ./scripts/build.sh
      shell: bash
